backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "products"
    label: "Products"
    folder: "src/pages/product"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "select", default: "product-page", options: [{ label: "Product Page", value: 'product-page'}, { label: "Accessories Page", value: 'accessory-page'}]}
      - {label: "Collection Name", name: "collectionKey", widget: "hidden", default: "products"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Banner Image", name: "bannerImage", widget: "image"}
      - {label: "Technical Specifications", name: "techSpecs", widget: "text"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: Finishes, name: finishes, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Name, name: name, widget: text}, {label: Caption, name: caption, widget: text}]}
      - {label: Gallery, name: gallery, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/homepage/index.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Banner Image", name: "bannerImage", widget: "image"}
          - {label: Gallery, name: gallery, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "full-width-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: "bannerImage", widget: "image"}
          - {label: "Attachment", name: "attachment", widget: "object", fields: [{ label: File, name: file, widget: file}, {label: Text, name: text, widget: text}]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: "bannerImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/distributors/index.md"
        label: "Distributors"
        name: "distributors"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "full-width-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: "bannerImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Product Page"
        name: "product-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "collections-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Banner Image", name: "bannerImage", widget: "image"}
      - file: "src/pages/gallery/index.md"
        label: "Gallery"
        name: "gallery"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-page"}
          - {label: Title, name: "title", widget: "string"}
          - {label: Images, name: "images", widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}] }
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/brochure/index.md"
        label: "Brochure"
        name: "brochure"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "brochure-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: "bannerImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/brochure/thanks.md"
        label: "Brochure Thank You"
        name: "brochure-thanks"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "full-width-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: "bannerImage", widget: "image"}
          - {label: "Attachment", name: "attachment", widget: "object", fields: [{ label: File, name: file, widget: file}, {label: Text, name: text, widget: text}]}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "siteMetadata"
    label: "Site Metadata"
    files:
      - file: "src/siteMetadata/navigation.md"
        label: "Navigation"
        name: "navigation"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "no-op"}
          - {label: "File Key", name: "fileKey", widget: "hidden", default: "navigation"}
          - label: "Navigation Items"
            name: "navItems"
            widget: "list"
            fields:
              - {label: "Page Title", name: title, widget: string }
              - {label: Path, name: to, widget: string }
              - {label: "Child Collection", name: childCollection, widget: string, default: "" }